# Local Development Configuration
# Replace the placeholder values with your actual credentials

spring:
  # Database Configuration (Using H2 for quick setup)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# AWS S3 Configuration
aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_BUCKET_NAME:textile-images-dev}
    base-url: https://${aws.s3.bucket-name}.s3.${aws.region}.amazonaws.com

# AI API Configuration - Using Gemini only
ai:
  google:
    gemini:
      api-key: ${GOOGLE_GEMINI_API_KEY}
      api-url: ${GOOGLE_GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/}
      model: ${GOOGLE_GEMINI_MODEL:gemini-2.5-flash-image}
      timeout: 60000

# CORS Configuration
app:
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  # File Storage Configuration
  file-storage:
    use-local: true  # Use local file storage instead of AWS S3
    local-path: uploads  # Directory for local file storage

# Logging Configuration
logging:
  level:
    com.textiletryon: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

