# Local Development Configuration
# Replace the placeholder values with your actual credentials

spring:
  profiles:
    active: local
  
  # Database Configuration (CHANGE THESE)
  datasource:
    url: jdbc:mysql://localhost:3306/textile_tryon
    username: root  # Change to your MySQL username
    password: Inai@2025 # Change to your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# AWS S3 Configuration (CHANGE THESE)
aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  s3:
    bucket-name: textile-images-dev  # Create this bucket in AWS S3
    base-url: https://textile-images-dev.s3.us-east-1.amazonaws.com

# AI API Configuration (ALREADY CONFIGURED ✅)
ai:
  flux:
    api-key: c037aced-dc2e-4c44-9a3a-405741a274cd
    api-url: https://api.flux.ai/v1/
    timeout: 60000
  google:
    gemini:
      api-key: AIzaSyArpY6cRzLdnMh5kIWjws5j0-thX_Liyaw
      api-url: https://generativelanguage.googleapis.com/v1beta/
      model: gemini-2.0-flash
      timeout: 60000

# CORS Configuration
app:
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Logging Configuration
logging:
  level:
    com.textiletryon: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

